"""
Export optimized screw layouts from both methods to Ansys-compatible format.
This script prepares the data for WBS 4.1 (Ansys Validation).
"""
import json
import pandas as pd
from pathlib import Path
import numpy as np

BASE_DIR = Path(__file__).resolve().parent
ROOT_DIR = BASE_DIR.parent.parent
RESULTS_DIR = ROOT_DIR / "data" / "results"
OUTPUT_DIR = RESULTS_DIR / "ansys_exports"
OUTPUT_DIR.mkdir(exist_ok=True)

def export_pinn_layout():
    """Export PINN-optimized layout from diff-FEA log."""
    log_path = RESULTS_DIR / "lbracket_diff_fea_log.csv"
    if not log_path.exists():
        print(f"⚠️  {log_path} not found")
        return None
    
    df = pd.read_csv(log_path)
    # Get final (best) configuration
    final_row = df.loc[df['compliance'].idxmin()]
    
    layout = {
        "method": "pinn_diff_fea",
        "source_file": "lbracket_diff_fea_log.csv",
        "final_compliance_julia": float(final_row['compliance']),
        "iterations": int(final_row['iter']),
        "screws": [
            {"id": 1, "x_mm": float(final_row['s1_x']), "y_mm": float(final_row['s1_y'])},
            {"id": 2, "x_mm": float(final_row['s2_x']), "y_mm": float(final_row['s2_y'])}
        ],
        "geometry": {
            "type": "L_bracket",
            "thickness_mm": 25.0,
            "max_dim_mm": 100.0,
            "load_dof": 68,  # From lbracket.json
            "load_magnitude_N": -1000.0
        },
        "material": {
            "E_base_MPa": 70000.0,
            "E_bolt_MPa": 200000.0,
            "nu": 0.3,
            "thickness_mm": 5.0
        }
    }
    
    output_path = OUTPUT_DIR / "pinn_optimal_layout.json"
    with open(output_path, 'w') as f:
        json.dump(layout, f, indent=2)
    print(f"✅ Exported PINN layout to {output_path}")
    return layout

def export_mmc_layout():
    """Export MMC-optimized layout."""
    log_path = RESULTS_DIR / "mmc_lbracket_log.csv"
    if not log_path.exists():
        print(f"⚠️  {log_path} not found")
        return None
    
    df = pd.read_csv(log_path)
    # Get final configuration
    final_row = df.loc[df['compliance'].idxmin()]
    
    # MMC coordinates are in element indices, convert to mm
    # Assuming 40x40 grid over 100mm x 100mm domain
    scale_factor = 100.0 / 40.0  # mm per element
    
    layout = {
        "method": "mmc",
        "source_file": "mmc_lbracket_log.csv",
        "final_compliance_normalized": float(final_row['compliance']),
        "iterations": int(final_row['iter']),
        "screws": [
            {"id": 1, "x_mm": float(final_row['x1']) * scale_factor, 
             "y_mm": float(final_row['y1']) * scale_factor},
            {"id": 2, "x_mm": float(final_row['x2']) * scale_factor, 
             "y_mm": float(final_row['y2']) * scale_factor}
        ],
        "geometry": {
            "type": "L_bracket",
            "mesh_resolution": "40x40",
            "void_cutoff_x_elements": 16,
            "void_cutoff_y_elements": 16,
            "load_case": "horizontal_tip"
        },
        "material": {
            "E_base_normalized": 1.0,
            "E_bolt_normalized": 5.0,
            "nu": 0.3
        },
        "note": "MMC uses normalized compliance. Physical units require scaling factor."
    }
    
    output_path = OUTPUT_DIR / "mmc_optimal_layout.json"
    with open(output_path, 'w') as f:
        json.dump(layout, f, indent=2)
    print(f"✅ Exported MMC layout to {output_path}")
    return layout

def create_ansys_script_template():
    """Create a template APDL script for Ansys validation."""
    template = """! Ansys APDL Script Template for L-Bracket Validation
! Generated by Export_Ansys_Layouts.py
! 
! This script loads the optimized screw positions and runs FEA validation.
! 
! STEP 1: Load geometry (L-bracket from CAD)
/prep7
! Import geometry or define manually based on lbracket.json

! STEP 2: Define material properties
MP,EX,1,70000    ! Base material (Aluminum) - MPa
MP,PRXY,1,0.3
MP,EX,2,200000   ! Bolt material (Steel) - MPa  
MP,PRXY,2,0.3

! STEP 3: Apply screw positions (from exported JSON)
! Screw 1: x={s1_x}, y={s1_y}
! Screw 2: x={s2_x}, y={s2_y}
! Create circular regions at these positions with radius=5mm

! STEP 4: Mesh
! Use appropriate element type (PLANE182 or SOLID186)
! Refine mesh around screw locations

! STEP 5: Boundary conditions
! Fix top edge of vertical leg (matching lbracket.json fixed_dofs)
! Apply load at tip of horizontal leg: -1000N in Y direction

! STEP 6: Solve
/solu
solve

! STEP 7: Extract compliance
/post1
! Compliance = 0.5 * F^T * U
! Compare with Julia/MMC predictions

! Expected compliance from Julia: ~939 J
! Expected compliance from MMC: ~0.43 (normalized, needs conversion)
"""
    
    output_path = OUTPUT_DIR / "ansys_validation_template.txt"
    with open(output_path, 'w') as f:
        f.write(template)
    print(f"✅ Created Ansys template at {output_path}")

def main():
    print("=== Exporting Optimized Layouts for Ansys Validation ===\n")
    
    pinn_layout = export_pinn_layout()
    mmc_layout = export_mmc_layout()
    
    # Create comparison summary
    if pinn_layout and mmc_layout:
        summary = {
            "export_timestamp": pd.Timestamp.now().isoformat(),
            "methods": {
                "pinn": {
                    "final_compliance": pinn_layout["final_compliance_julia"],
                    "screws": pinn_layout["screws"],
                    "iterations": pinn_layout["iterations"]
                },
                "mmc": {
                    "final_compliance_normalized": mmc_layout["final_compliance_normalized"],
                    "screws": mmc_layout["screws"],
                    "iterations": mmc_layout["iterations"]
                }
            },
            "validation_target": {
                "error_threshold_percent": 15.0,
                "note": "Compare Ansys results with Julia predictions. MMC values are normalized."
            }
        }
        
        summary_path = OUTPUT_DIR / "validation_summary.json"
        with open(summary_path, 'w') as f:
            json.dump(summary, f, indent=2)
        print(f"✅ Created validation summary at {summary_path}")
    
    create_ansys_script_template()
    
    print("\n✅ Export complete! Files ready for Ansys validation (WBS 4.1)")

if __name__ == "__main__":
    main()

